# Banco
spring.datasource.url=jdbc:postgresql://localhost:5433/canil_db
spring.datasource.username=canil_user
spring.datasource.password=canil_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=false

# JWT
jwt.secret=canil-alto-bela-vista-secret-key-dev-256-bits-minimo
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Cloudinary
cloudinary.cloud-name=dfrt0mwue
cloudinary.api-key=653737229867927
cloudinary.api-secret=OdrULJjyUyqSFTjpUVf2iIJldvg